"""revised the department attributes

Revision ID: 060ff15afcf7
Revises: f1b19b2dd682
Create Date: 2024-07-16 22:32:08.770301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '060ff15afcf7'
down_revision = 'f1b19b2dd682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_department', sa.String(length=100), nullable=False))
        batch_op.drop_column('department')
        batch_op.drop_column('username')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('faculty_department', sa.String(length=255), nullable=False))
        batch_op.drop_index('school_id')
        batch_op.create_unique_constraint(None, ['faculty_id'])
        batch_op.drop_column('department')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=100), nullable=False))
        batch_op.drop_index('school_id')
        batch_op.create_unique_constraint(None, ['student_id'])
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('school_id', ['school_id'], unique=True)
        batch_op.drop_column('student_id')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('department', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('school_id', ['school_id'], unique=True)
        batch_op.drop_column('faculty_department')
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('department', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('admin_department')

    # ### end Alembic commands ###
