"""fix the contact number attrib

Revision ID: 11de894d7b70
Revises: 6a2265708eee
Create Date: 2024-07-17 01:05:38.944774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11de894d7b70'
down_revision = '6a2265708eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_information', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_information', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
