"""add totp_token_used on user model

Revision ID: 7ac25ac7090f
Revises: 
Create Date: 2024-10-04 18:15:21.556466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ac25ac7090f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('totp_secret', schema=None) as batch_op:
        batch_op.drop_index('secret_hex')
        batch_op.drop_column('secret_hex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('totp_secret', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_hex', mysql.VARCHAR(length=32), nullable=False))
        batch_op.create_index('secret_hex', ['secret_hex'], unique=True)

    # ### end Alembic commands ###
