"""added school_id for admin

Revision ID: 8399fa9aa10c
Revises: 060ff15afcf7
Create Date: 2024-07-16 23:18:22.536475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8399fa9aa10c'
down_revision = '060ff15afcf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['school_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
