"""added a designation attrib on faculty

Revision ID: aeb3e66e11b6
Revises: f2693b063470
Create Date: 2024-07-17 21:53:17.473670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb3e66e11b6'
down_revision = 'f2693b063470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('designation')

    # ### end Alembic commands ###
