"""first migrate

Revision ID: f1b19b2dd682
Revises: 
Create Date: 2024-07-16 21:59:45.146120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b19b2dd682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid_uid', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=False),
    sa.Column('l_name', sa.String(length=100), nullable=False),
    sa.Column('m_name', sa.String(length=100), nullable=False),
    sa.Column('m_initial_', sa.String(length=5), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'faculty', 'admin'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=False),
    sa.Column('civil_status', sa.String(length=15), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('citizenship', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('religion', sa.String(length=255), nullable=False),
    sa.Column('dialect', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.Column('h_city', sa.String(length=255), nullable=False),
    sa.Column('h_barangay', sa.String(length=255), nullable=False),
    sa.Column('h_house_no', sa.Integer(), nullable=False),
    sa.Column('h_street', sa.String(length=255), nullable=False),
    sa.Column('curr_city', sa.String(length=255), nullable=True),
    sa.Column('curr_barangay', sa.String(length=255), nullable=True),
    sa.Column('curr_house_no', sa.Integer(), nullable=True),
    sa.Column('curr_street', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('user_educational_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elem_school', sa.String(length=255), nullable=False),
    sa.Column('elem_address', sa.String(length=255), nullable=False),
    sa.Column('elem_graduated', sa.Integer(), nullable=False),
    sa.Column('junior_school', sa.String(length=255), nullable=True),
    sa.Column('junior_address', sa.String(length=255), nullable=True),
    sa.Column('junior_graduated', sa.Integer(), nullable=True),
    sa.Column('senior_school', sa.String(length=255), nullable=False),
    sa.Column('senior_address', sa.String(length=255), nullable=False),
    sa.Column('senior_graduated', sa.Integer(), nullable=False),
    sa.Column('senior_track_strand', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_family_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mother_full_name', sa.String(length=255), nullable=False),
    sa.Column('mother_educ_attainment', sa.String(length=255), nullable=True),
    sa.Column('mother_addr', sa.String(length=255), nullable=True),
    sa.Column('mother_brgy', sa.String(length=255), nullable=True),
    sa.Column('mother_cont_no', sa.String(length=255), nullable=True),
    sa.Column('mother_place_work_or_company_name', sa.String(length=255), nullable=True),
    sa.Column('mother_occupation', sa.String(length=255), nullable=True),
    sa.Column('father_full_name', sa.String(length=255), nullable=True),
    sa.Column('father_educ_attainment', sa.String(length=255), nullable=True),
    sa.Column('father_addr', sa.String(length=255), nullable=True),
    sa.Column('father_brgy', sa.String(length=255), nullable=True),
    sa.Column('father_cont_no', sa.String(length=255), nullable=True),
    sa.Column('father_place_work_or_company_name', sa.String(length=255), nullable=True),
    sa.Column('father_occupation', sa.String(length=255), nullable=True),
    sa.Column('guardian_full_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_educ_attainment', sa.String(length=255), nullable=True),
    sa.Column('guardian_addr', sa.String(length=255), nullable=True),
    sa.Column('guardian_brgy', sa.String(length=255), nullable=True),
    sa.Column('guardian_cont_no', sa.String(length=255), nullable=True),
    sa.Column('guardian_place_work_or_company_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_occupation', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course_and_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('year_level', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=False),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'late'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['course_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_lab_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'), nullable=False),
    sa.Column('schedule_from', sa.Time(), nullable=False),
    sa.Column('schedule_to', sa.Time(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['course_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_lab_schedules')
    op.drop_table('attendance')
    op.drop_table('student_course_and_year')
    op.drop_table('course_subjects')
    op.drop_table('user_family_background')
    op.drop_table('user_educational_background')
    op.drop_table('student')
    op.drop_table('faculty')
    op.drop_table('contact_information')
    op.drop_table('admin')
    op.drop_table('user')
    # ### end Alembic commands ###
