"""updated some attributes

Revision ID: f2693b063470
Revises: 9e90114fc86b
Create Date: 2024-07-17 18:18:56.676399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2693b063470'
down_revision = '9e90114fc86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_educational_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tertiary_school', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('tertiary_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('tertiary_graduated', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('tertiary_course', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_educational_background', schema=None) as batch_op:
        batch_op.drop_column('tertiary_course')
        batch_op.drop_column('tertiary_graduated')
        batch_op.drop_column('tertiary_address')
        batch_op.drop_column('tertiary_school')

    # ### end Alembic commands ###
